### ISSUE TITLE
A lot of boilerplate code

### ISSUE THREAD

**Issue by lprhodes** [creationix/gen-run#12]
Hi,

Thanks for sharing this code, really enjoying the simplistic way of yielding here.

I look to be writing the following a lot and I wanted to check that I wasn't missing something before I went ahead and created a method to make this easier.

```
Class.prototype.method = function(some, arguments) {
    const self = this;  

    return function(callback) {
        run(function* (genCallback) {
            //Code with yielding inside

             callback(null, obj);
        });
    });
}
```

**Comment by creationix** [comment]
In js-git the style I like is to make functions that work in wither node.js style callbacks or return continuables.  A typical function looks like:

``` js
function doThing(arg1, arg2, callback) {
  // Return a continuable if no callback is passed in
  if (!callback) return doThing.bind(this, arg1, arg2);
  // All code in here is normal callback style code
  callback(err, result);
}
```

This is library code where I can't depend on generator syntax, but want to play nicely with both ecosystems.  The one-line at the top is nice because it doesn't increase indentation.

Now if you're writing an app and can use generator syntax, then I recommend writing your methods as generators directly.

``` js
function* myFunction(arg1, arg2) {
  // Calling a hybrid function requires a normal yield since it returns a continuable.
  var result = yield doThing(1, 2);
  // But calling other generator functions is yield* so that it can yield on your behalf
  var another = yield* generatorFunction("stuff", "to", "pass")
}
```

Since I was binding the this value in the hybrid case, this technique also works for prototype methods that need the dynamic `this` preserved.

Now if you really want to write functions that externally are hybrid but internally use generators, then I would do it like this:

``` js
Class.prototype.method = function method(some, arguments, callback) {
  if (!callback) return method.bind(this, some, arguments);
  var self = this;
  run(function* () {
    // body with yields here
    if (problem) throw new Error("some message");
    return result;
  }, callback);
};
```

Notice that within the generator body, I use throw and return, not the callback.  I simply pass the callback to gen-run which handles the routing for you.

If you were doing this for a large number of methods, I would write a wrapper since the gen-run API isn't ideal for this case.

Here is one way for when you don't need hybrid methods, but always return a continuable:

``` js
function wrap(gen) {
  return function () {
    var self = this;
    var args = arguments;
    return function (callback) {
      run(gen.apply(self, args), callback);
    };
  };
}
```

And it's used like:

``` js
Class.prototype.method = wrap(function* (some, args) {
  // this is preserved and can be used normally
  // the arguments are used normally
  // you can use throw or return to send (err, value) to the hidden callback
});
```

**Comment by creationix** [comment]
If you did want hybrid the last helper would either need to assume that arguments are never functions and that only a callback would be a function in the last position or you could specify the fixed number of arguments in the wrapper. `wrap2(function* (a, b) {})`.

``` js
function wrap2(gen) {
  return function wrapped(a, b, callback) {
    if (!callback) return wrapped.bind(this, a, b);
    run(gen.call(this, a, b), callback);
  }
}
```

**Comment by lprhodes** [comment]
Such a detailed response, thanks for all of the great info!
